name: Snowballer
main: co.networkery.uvbeenzaned.Snowballer
version: 1.5.1
commands:
   snowballer:
       description: Main Snowballer command.
       aliases: [sbr]
       usage: |
         ----Snowballer Help----
         /<command> join cyan to join the cyan team.
         /<command> join lime to join the lime team.
         /<command> leave to leave your current team.
         /<command> score to check your current score.